name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Zip Folder
      run: zip -r aditum-opencart-${{ steps.get_version.outputs.VERSION }}.ocmod.zip install.xml upload README.md